# fly.toml app configuration file generated for little-violet-5641 on 2023-09-07T22:20:35+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "little-violet-5641"
primary_region = "ams"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
